apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: jpuv-system
data:
  fluent-bit.conf: |

    [SERVICE]
        Flush 5
        Log_Level info
        Parsers_File parsers.conf
        Daemon Off
        HTTP_Server On
        HTTP_Listen 0.0.0.0
        HTTP_Port 2020
        Health_check On

    @INCLUDE input-kubernetes.conf
    @INCLUDE filter-kubernetes.conf
    @INCLUDE output.conf
    @INCLUDE parsers.conf

  input-kubernetes.conf: |

    [INPUT]
        Name tail
        Path /var/log/containers/*.log, /var/log/pods/*.log
        Tag kube.*
        Refresh_Interval 10
        multiline.Parser docker, cri, json, custom_time_parser
        Mem_Buf_Limit 5MB
        Skip_Long_Lines On

    [INPUT]
        Name cpu
        Tag cpu.local
        Parser cpu_parser

  filter-kubernetes.conf: |

    [FILTER]
        Name kubernetes
        Match kube.*
        #Kube_Tag_Prefix     kube.var.log.containers.
        #Kube_URL            https://kubernetes.default.svc:443
        #Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        #Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Merge_Log On
        Keep_Log Off
        K8S-Logging.Parser On
        K8S-Logging.Exclude On
        Annotations Off

        #[FILTER]
        # Name            nest
        #Match           kube.*
        #Operation       lift
        #Nested_under    kubernetes
        #Add_prefix      kubernetes_

        #[FILTER]
        #Name            nest
        #Match           kube.*
        #Operation       lift
        #Nested_under    kubernetes_labels
        #Add_prefix      kubernetes_labels_
  output.conf: |

     [OUTPUT]
        Name opensearch
        Match kube.*
        Host 
        Port 443
        #HTTPS_User      ${OPENSEARCH_USER}
        #HTTPS_Passwd    ${OPENSEARCH_PASSWORD}
        HTTP_User 
        HTTP_Passwd 
        Index fluent-bit
        TLS On
        #AWS_Auth On
        TLS.Verify Off
        Type _doc
        #write_operation index
        #Time_Key        @timestamp
        Suppress_Type_Name On
        Trcae_Error On
        AWS_Service_Name aoss
        AWS_Region us-east-1
        Replace_Dots On
        Retry_Limit False

     [OUTPUT]
        Name stdout
        Match *

  parsers.conf: |

     [PARSER]
        Name custom_time_parser
        Format regex
        Regex ^test-log (?<log_time>.*)$
        Time_key log_time
        Time_Format %a %b %d %I:%M:%S %p %Z %Y

     [PARSER]
        Name cpu_parser
        Format json
        Time_key timestamp
        Time_Format %s.%L
        Time_Key_Keep On

     [PARSER]
        Name docker
        Format json
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep Off

     [PARSER]
        Name json
        Format json
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep Off

     [PARSER]
        Name cri
        Format regex
        Regex ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<log>.*)$
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S.%L%Z
