apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit
  namespace: jpuv-system
  labels:
    k8s-app: fluent-bit
spec:
  selector:
    matchLabels:
      name: fluent-bit
  template:
    metadata:
      labels:
        name: fluent-bit
    spec:
      serviceAccountName: fluent-bit
      containers:
        - name: fluent-bit
          image: 'fluent/fluent-bit:3.2.8-debug'
          envFrom:
            - secretRef:
                name: fluent-bit-secret
          volumeMounts:
            - name: varlog
              mountPath: /var/log/pods
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
            - name: varlogcontainers
              mountPath: /var/log/containers
            - name: config
              mountPath: /fluent-bit/etc/fluent-bit

      volumes:
        - name: varlog
          hostPath:
            path: /var/log/pods
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: varlogcontainers
          hostPath:
            path: /var/log/containers
        - name: config
          configMap:
            name: fluent-bit-config
